cc_library(
  name = "geometry",
  hdrs = [
    "concepts.h",
    "enums.h",
    "expressions.h",
    "iteration.h",
    "shape_node.h",
  ],
  deps = [
    "//game/common:types",
    "//game/common:math",
    "@glm",
  ],
  visibility = ["//game/logic:__subpackages__"],
)
