cc_library(
  name = "geometry",
  hdrs = [
    "enums.h",
    "geometry.h",
  ],
  deps = [
    "//game/common:types",
    "//game/common:math",
    "@glm",
  ],
  visibility = ["//game/logic:__subpackages__"],
)
