cc_library(
  name = "setup",
  hdrs = ["setup.h"],
  srcs = ["setup.cc"],
  deps = ["//game/logic/sim:setup"],
  implementation_deps = [
    "//game/logic/sim:sim_interface",
    "//game/logic/v0/overmind",
    "//game/logic/v0/player",
  ],
  visibility = ["//game/logic/sim:__pkg__"],
)