load("//test:replay_test.bzl", "replay_test")

replay_test(
  replay = "replays/1p_hardmode_HARDMAN_367210.wrp",
  score = 367210,
)

replay_test(
  replay = "replays/bossmode.wrp",
  score = 39291,
)

replay_test(
  replay = "replays/BEEF_373295.wrp",
  score = 373295,
)

replay_test(
  replay = "replays/Darb_2p__Graves__Darb_553403.wrp",
  score = 553403,
)

replay_test(
  replay = "replays/Darb_4p__Team_Graves_430987.wrp",
  score = 430987,
)

replay_test(
  replay = "replays/inputswap_40750.wrp",
  score = 40750,
)

replay_test(
  replay = "replays/seiken_1p__crikey_641530.wrp",
  score = 641530,
)

replay_test(
  replay = "replays/seiken_2p__RAB__STU_Yo_477833.wrp",
  score = 477833,
)

replay_test(
  replay = "replays/seiken_3p__3_OF_US_219110.wrp",
  score = 219110,
)

replay_test(
  replay = "replays/STU_542570.wrp",
  score = 542570,
)
