cc_library(
  name = "legacy",
  hdrs = [
    "attachment_point.h",
    "ball_collider.h",
    "box.h",
    "line.h",
    "ngon.h",
    "polyarc.h",
  ],
  deps = [
    "//game/geometry",
    "//game/common:types",
    "//game/common:math",
    "//game/render/data",
    "@glm",
  ],
  visibility = ["//game/logic/legacy:__subpackages__"],
)
