cc_library(
  name = "data",
  hdrs = [
    "background.h",
    "panel.h",
    "shapes.h",
    "text.h",
  ],
  deps = [
    "//game/common:math",
    "//game/common:types",
    "//game/common:ustring",
  ],
  visibility = ["//visibility:public"],
)
