cc_library(
  name = "player",
  hdrs = ["player.h"],
  srcs = ["player.cc"],
  deps = [
    "//game/common:math",
    "//game/logic/ecs",
    "//game/logic/sim/io:player",
  ],
  visibility = ["//game/logic/v0:__pkg__"],
)