load("//deps:xxd.bzl", "xxd")

xxd(
  name = "shaders",
  namespace = "ii::render::shaders",
  srcs = [
    "line.f.glsl",
    "line.v.glsl",
    "rect.f.glsl",
    "rect.v.glsl",
    "text.f.glsl",
    "text.v.glsl",
  ],
  visibility = ["//visibility:public"],
)
