load("//tools:xxd.bzl", "xxd")

xxd(
  name = "fonts",
  namespace = "ii::assets::fonts",
  srcs = [
    "roboto_mono_bold.ttf",
    "roboto_mono_bold_italic.ttf",
    "roboto_mono_italic.ttf",
    "roboto_mono_regular.ttf",
  ],
  visibility = ["//visibility:public"],
)
