cc_library(
  name = "shapes",
  hdrs = [
    "ball.h",
    "box.h",
    "data.h",
    "line.h",
    "ngon.h",
  ],
  deps = [
    "//game/geometry",
    "//game/common:types",
    "//game/common:math",
    "//game/render/data",
    "@glm",
  ],
  visibility = ["//game:__subpackages__"],
)
