cc_library(
  name = "formations",
  hdrs = ["formations.h"],
  deps = [
    "//game/logic/v0/enemy",
    "//game/logic/v0/overmind:internal",
  ],
  visibility = ["//game/logic/v0/overmind:__pkg__"],
)