cc_library(
  name = "gl",
  hdrs = [
    "data.h",
    "draw.h",
    "program.h",
    "texture.h",
    "types.h",
  ],
  deps = [
    "//game/common:types",
    "@gl3w",
    "@glm",
  ],
  visibility = ["//game/render:__pkg__"],
)