cc_library(
  name = "ecs",
  hdrs = [
    "call.h",
    "detail.h",
    "id.h",
    "index.h",
    "index.i.h",
  ],
  deps = ["//game/common:types"],
  visibility = ["//game/logic:__subpackages__"],
)