cc_library(
  name = "shapes",
  hdrs = [
    "ball.h",
    "box.h",
    "data.h",
    "line.h",
    "ngon.h",
  ],
  deps = [
    "//game/logic/geometry",
    "//game/logic/sim/io:render",
    "//game/common:types",
    "//game/common:math",
    "@glm",
  ],
  visibility = ["//game/logic/v0:__subpackages__"],
)
