cc_library(
  name = "shapes",
  hdrs = [
    "attachment_point.h",
    "ball_collider.h",
    "base.h",
    "box.h",
    "line.h",
    "ngon.h",
    "polyarc.h",
    "shapes.h",
  ],
  deps = [
    "//game/logic/geometry",
    "//game/common:types",
    "//game/common:math",
    "@glm",
  ],
  visibility = ["//game/logic:__subpackages__"],
)
