cc_library(
  name = "fx",
  hdrs = ["stars.h"],
  srcs = ["stars.cc"],
  deps = ["@glm"],
  implementation_deps = ["//game/logic/sim:sim_interface"],
  visibility = ["//game/logic:__subpackages__"],
)