cc_library(
  name = "overmind",
  hdrs = ["overmind.h"],
  srcs = ["overmind.cc"],
  implementation_deps = [
    "//game/common:math",
    "//game/logic/v0/enemy",
    "//game/logic/ship:components",
    "//game/logic/sim:sim_interface",
    "//game/logic/sim/io:conditions",
  ],
  visibility = ["//game/logic/v0:__pkg__"],
)