cc_library(
  name = "font",
  hdrs = ["font.h"],
  srcs = ["font.cc"],
  deps = [
    "//game/common:types",
    "//game/common:ustring",
    "@glm",
  ],
  implementation_deps = ["@freetype"],
  visibility = ["//visibility:public"],
)