cc_library(
  name = "font",
  hdrs = ["font.h"],
  srcs = ["font.cc"],
  deps = [
    "//game/common:types",
    "//game/common:ustring",
    "@freetype2",
    "@glm",
    "@span_lite",
  ],
  visibility = ["//visibility:public"],
)