load("//test:replay_test.bzl", "replay_test")

replay_test(replay = "//test/replays:Darb_1p__Darb_426680.wrp", score = 426680)
replay_test(replay = "//test/replays:DrakeGraves_1p__Graves_400670.wrp", score = 400670)
replay_test(replay = "//test/replays:DrakeGraves_1p__Graves_498305.wrp", score = 498305)
replay_test(replay = "//test/replays:seiken_1p__SEIKEN_419035.wrp", score = 419035)
replay_test(replay = "//test/replays:seiken_1p__Take_This_Graves_555985.wrp", score = 555985)
replay_test(replay = "//test/replays:seiken_2p__BOOBS_437203.wrp", score = 437203)
replay_test(replay = "//test/replays:seiken_2p__RabStu_321225.wrp", score = 321225)