cc_library(
  name = "mixer",
  hdrs = ["mixer.h"],
  srcs = ["mixer.cc"],
  deps = [
    "//game/common:types",
    "@dr_libs//:dr_wav",
    "@glm",
    "@libsamplerate",
  ],
  visibility = ["//visibility:public"],
)

cc_library(
  name = "sound",
  hdrs = ["sound.h"],
  visibility = ["//visibility:public"],
)