cc_library(
  name = "geom2",
  hdrs = [
    "enums.h",
    "resolve.h",
    "shape_bank.h",
    "shape_data.h",
    "transform.h",
    "value_parameters.h",
  ],
  srcs = ["shape_bank.cc"],
  deps = [
    "//game/common:math",
    "//game/common:types",
    "//game/render/data",
  ],
  visibility = ["//game:__subpackages__"],
)