name: Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            config: gcc
            command: sudo apt-get update && sudo apt-get install -y libsdl2-dev
          - os: ubuntu-22.04
            config: clang
            command: sudo apt-get update && sudo apt-get install -y libsdl2-dev
          - os: windows-2022
            config: msvc
            command: true
          - os: windows-2022
            config: clang-cl
            command: true
          - os: windows-2022
            config: ubsan-cl
            command: true
          - os: macos-12
            config: darwin
            command: brew install sdl2 && export BAZEL_USE_CPP_ONLY_TOOLCHAIN=1
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: ${{ matrix.command }}
    - run: bazel build --config ci --config ${{ matrix.config }} //game //game:tools && ls bazel-bin/game
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.config }}-tools
        path: bazel-bin/game/tools.zip
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.config }}-game
        path: bazel-bin/game/game.zip
    - run: bazel test --config ci --config ${{ matrix.config }} //test/...
