load("//test:network_sim_test.bzl", "network_sim_test")

network_sim_test(replay = "//test/replays:Darb_2p__Graves__Darb_553403.wrp", topology = "AB")
network_sim_test(replay = "//test/replays:Darb_4p__Team_Graves_430987.wrp", topology = "ABAB")
network_sim_test(replay = "//test/replays:seiken_2p__RAB__STU_Yo_477833.wrp", topology = "AB")
network_sim_test(replay = "//test/replays:seiken_3p__3_OF_US_219110.wrp", topology = "ABC")